twig:
    file_name_pattern: '*.twig'
    globals:
        banner_repository: '@App\Repository\BannerRepository'

when@dev:
    twig:
        debug: true
        strict_variables: true

when@test:
    twig:
        strict_variables: true
