[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_mysql", "php83Extensions.intl", "php83Extensions.zip", "php83Extensions.gd", "php83Extensions.mbstring", "php83Extensions.xml", "php83Extensions.curl"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "php bin/console cache:clear --env=prod",
    "php bin/console assets:install --env=prod"
]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} -t public"
